(module students
    (student-list avoid-pairs prefer-pairs)
  
  (import chicken)
  (import scheme)
  
  (define avoid-pairs
    '((noah  liam      9999)
      (noah  mason     9999)
      (ethan michael   9999)))

  (define prefer-pairs
    '((emma     mason     1)
      (emma     olivia    1)
      (emma     sophia    1)
      (olivia   isabella  1)
      (elijah   jacob     3)
      (emily    mia       3)
      (sophia   isabella  1)
      (sophia   mia       1)
      (isabella harper    3)))
  
  (define student-list
    '((noah    ((gender m)
                (ethnicity w)))
      (liam    ((gender m)
                (ethnicity w)))
      (mason   ((gender m)
                (ethnicity w)))
      (ethan   ((gender m)
                (ethnicity w)))
      (michael ((gender m)
                (ethnicity c)))
      (jacob   ((gender m)
                (ethnicity c)))
      (elijah  ((gender m)
                (ethnicity w)))
      (aidan   ((gender m)
                (ethnicity w)))
      (alexander ((gender m)
                  (ethnicity c)))
      (jayden  ((gender m)
                (ethnicity c)))
      
      (emma     ((gender f)
                 (ethnicity c)))
      (olivia   ((gender f)
                 (ethnicity w)))
      (sophia   ((gender f)
                 (ethnicity w)))
      (isabella ((gender f)
                 (ethnicity v)))
      (ava      ((gender f)
                 (ethnicity w)))
      (mia      ((gender f)
                 (ethnicity k)))
      (emily    ((gender f)
                 (ethnicity w)))
      (abagail  ((gender f)
                 (ethnicity j)))
      (madison  ((gender f)
                 (ethnicity f)))
      (harper   ((gender f)
                 (ethnicity c)))))

  )
