(module students
    (student-list avoid-pairs prefer-pairs)
  
  (import chicken)
  (import scheme)
  
  (define avoid-pairs
    '((noah  liam      9999)
      (noah  mason     9999)
      (ethan michael   9999)))

  (define prefer-pairs
    '((olivia   george    -10)
      (olivia   kiki      -10)
      (olivia   luna      -10)
      (olivia   jaydenc   -10)
      (jayden   alexander -7)
      (emily    abagail   -7)
      (sophia   isabella  -10)
      (sophia   mia       -10)
      (isabella mia       -7)))
  
  (define student-list
    '((noah    ((gender m)
                (ethnicity w)))
      (liam    ((gender m)
                (ethnicity w)))
      (mason   ((gender m)
                (ethnicity w)))
      (ethan   ((gender m)
                (ethnicity w)))
      (michael ((gender m)
                (ethnicity c)))
      (jacob   ((gender m)
                (ethnicity c)))
      (elijah  ((gender m)
                (ethnicity w)))
      (aidan   ((gender m)
                (ethnicity w)))
      (alexander ((gender m)
                  (ethnicity c)))
      (jayden  ((gender m)
                (ethnicity c)))
      
      (emma     ((gender f)
                 (ethnicity c)))
      (olivia   ((gender f)
                 (ethnicity w)))
      (sophia   ((gender f)
                 (ethnicity w)))
      (isabella ((gender f)
                 (ethnicity v)))
      (ava      ((gender f)
                 (ethnicity w)))
      (mia      ((gender f)
                 (ethnicity k)))
      (emily    ((gender f)
                 (ethnicity w)))
      (abagail  ((gender f)
                 (ethnicity j)))
      (madison  ((gender f)
                 (ethnicity f)))
      (harper   ((gender f)
                 (ethnicity c)))))

  )
